version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: wget https://github.com/XDMEOW/MCBOT && cd MCBOT && java -jar MCBOT.jar play.valocraft.xyz 47 nullping -1 -1
